apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "document-processor.fullname" . }}
  labels:
    {{- include "document-processor.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.configMap.logLevel | quote }}
  S3_BUCKET_NAME: {{ .Values.configMap.s3BucketName | quote }}
  SQS_QUEUE_URL: {{ .Values.configMap.sqsQueueUrl | quote }}
  AWS_REGION: {{ .Values.configMap.awsRegion | quote }}
  ENABLE_FEATURE_X: {{ .Values.configMap.enableFeatureX | quote }}
