apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-processor.fullname" . }}
  labels:
    {{- include "document-processor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "document-processor.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
    - name: http-metrics
      port: {{ .Values.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
